name: jericho_plays
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  just_audio: ^0.9.39
  google_fonts: ^6.2.1
  sqflite: ^2.3.3+1
  path: ^1.9.0
  flutter_native_splash: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_svg: ^2.0.10+1

  flutter_lints: ^3.0.0


flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/audio/
    - assets/

flutter_native_splash:
  image: assets/images/music_logo_design_1.png
  color: "#EBF3EB"


